SmartphoneShop/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SmartphoneShop.Data;
using SmartphoneShop.Services;
using SmartphoneShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SmartphoneShop.Controllers
{
    public class AppController : Controller
    {
        private readonly IMailService _mailService;
        private readonly ISmartphoneRepository _repository;

        public AppController(IMailService mailService, ISmartphoneRepository repository)
        {
            _mailService = mailService;
            _repository = repository;
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Send the email
                _mailService.SendMessage("romanpanshyn@gmail.com", model.Subject, $"From: {model.Name} - {model.Email}, Message: {model.Message}");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }

            return View();
        }

        public IActionResult About()
        {
            ViewBag.Title = "About Us";

            return View();
        }

        public IActionResult Shop()
        {
            ViewBag.Title = "Shop";

            return View();
        }

    }
}

SmartphoneShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Smartphone Shop: @ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <h1 class="navbar-brand"><i class="fa fa-mobile"></i> Smartphone Shop</h1>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="App" asp-action="Shop">Shop</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="App" asp-action="About">About</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>
    <footer class="container">
        <div class="text-center">Copyright 2020 Smartphone Shop LLC</div>
    </footer>


    <script src="~/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts", false)
</body>
</html>